# Generated by Django 3.1.3 on 2022-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int', models.IntegerField(max_length=100)),
                ('char', models.CharField(max_length=100)),
                ('desimal', models.FloatField()),
                ('text', models.TextField()),
            ],
        ),
    ]
